### PR TITLE
rbenv support

### PR DESCRIPTION
**Pull request by jeroenhouben**
There is a cap variable called **bundle_cmd** which I think should be used. That way the bundle command becomes flexible and can be used by capistrano-rbenv to inject a different command for running bundle (exec)

### CODE REVIEW

**Comment by sosedoff** [comment]
In what capistrano release this variable was introduced?

**Comment by jeroenhouben** [comment]
It's actually part of bundler

https://github.com/carlhuda/bundler/blob/master/lib/bundler/deployment.rb

**Comment by franciscoj** [comment]
Any change that this get merged? I was about to fork it myself when I just found it :smile:

**Comment by franciscoj** [comment]
Thanks a lot!

**Comment by sosedoff** [comment]
Im having a trouble with `bundle_cmd`. Using bundler v1.2.1 i get error `undefined local variable or method 'bundle_cmd'`. Deploy script requires `bundler/capistrano`.

Anybody else having this issue ?

**Comment by franciscoj** [comment]
I had it, but got it fixed by adding

``` ruby
set(:bundle_cmd) { 'bundle' }
```

to the deploy script

**Comment by sosedoff** [comment]
Yeah, i figured.

**Pull request merged**
