### PR TITLE
Configurable Roles

### PR DESCRIPTION
**Pull request by DaRizat**
I have added a new commit which incorporates some fixes from my last commit. I didn't intend for this to gain any type of attention (sorry for that) so I had some errors in the code that I committed that had to be fixed. I also updated the documentation to add the new option and describe the default behavior which is to perform tasks on the :app role. I also bumped the version number to 0.1.7. 

Thanks,
Jack

### CODE REVIEW

**Comment by aspiers** [comment]
This can't be merged any more, please can you rebase?

**Comment by DaRizat** [comment]
Rebase complete

**Comment by aspiers** [comment]
Sorry, but that's not a proper rebase, because it contains a merge commit.  You need to rebase on `origin/master` (after ensuring it's up-to-date).

**Comment by DaRizat** [comment]
Ok, how about now? I ran git rebase upstream/master, then fixed conflicts, then ran git rebase origin/master and it is saying everything is up to date.

**Comment by aspiers** [comment]
Now you have to `git push -f` to your github fork.

**Comment by DaRizat** [comment]
When I do that it just says everything up to date.

**Comment by DaRizat** [comment]
Any updates on what I should be doing here? Thanks!

**Comment by aspiers** [comment]
You must have done something wrong during the rebase, or rebased the wrong branch, or pushed the wrong branch, or pushed to the wrong remote.  The tip of this pull request is 1c17618 as shown above, and that is a merge commit.  A proper rebase results in a linear sequence of commits on top of `origin/master`, _with no merge commits_.  Run `gitk --all` and you'll see what I mean.  I strongly recommend you read [some git documentation](http://git-scm.com/book/en/Git-Branching-Rebasing) to learn about this properly.

**Pull request closed without merging**
