### PR TITLE
Add unicorn duplicate task

### PR DESCRIPTION
**Pull request by danielkman**
When using the [Github recommended procedure](https://github.com/blog/517-unicorn) for unicorn zero downtime deployment also mentioned in this [rails cast](http://railscasts.com/episodes/373-zero-downtime-deployment?view=asciicast), You want the old unicorn master quitting to be handled by the "before_fork" hook in the unicorn.rb config file. In order for us to do that we need a task that won't kill the old master just duplicate it.

### CODE REVIEW

**Comment by aspiers** [comment]
Sounds reasonable, but it can't be merged any more - please can you rebase and address my comments?

**Comment by danielkman** [comment]
not sure if I did it right but I squashed my commits into commit a5a7742e1a3af9492a631962beab36c871944c65

**Comment by aspiers** [comment]
Thanks but no, that's not quite right ;-)  You should have rebased not merged.  Try something like `git rebase -i origin/master`, then squash the typo fix and the main commit together, and kill the merge commit.  

I _strongly_ recommend reading [the relevant chapter of the git book](http://git-scm.com/book/en/Git-Branching-Rebasing). However the "Do not rebase commits that you have pushed to a public repository" warning it gives does not apply here - even though your forked branch is public, everyone involved (i.e. you and me) already knows that it is going to be rewritten, since that is an expected part of the review process.  So once you are done rebasing, you can safely `git push -f` to your forked branch and github will automatically update this pull request.

**Comment by danielkman** [comment]
Thanks for the help I think this is it

**Comment by aspiers** [comment]
Not quite ;-)  I think you didn't rebase against upstream because it still can't be merged.  Also you can drop the 'fix typo' from the commit message, because neither the typo nor its fix exist in the history any more.

**Comment by danielkman** [comment]
Thanks for being patient with me :)

I really hope this is it

**Comment by aspiers** [comment]
Awesome!  Thanks :)

**Pull request merged**
