### PR TITLE
fix multiple issues relating to variables

### LINKED ISSUE #7: You should set the pid path via the command line...
It'd be better if the pid path was set via the command line to match the value in the Capfile.

### LINKED ISSUE #46: `rails_env` / `unicorn_env` / `app_env` are redundant or undocumented
It's not at all clear why we need three variables which apparently serve the same purpose:
- `rails_env`
- `unicorn_env`
- `app_env`

If they are really all necessary and serve different purposes then they should be documented properly.  Otherwise they should be collapsed to just one variable, or two at most (since I can just about imagine that someone might want `unicorn_env` to have a different value to `rails_env`).

### LINKED ISSUE #64: Support for --no-default-middleware flag
``` ruby
  opts.on("-N", "--no-default-middleware",
          "do not load middleware implied by RACK_ENV") do |e|
    rackup_opts[:no_default_middleware] = true
  end
```

### PR DESCRIPTION
**Pull request by aspiers**
- fixes #46
  - documents the variables properly
  - renames misleading and broken app_env variable
- fixes #64 via a new unicorn_options variable
- fixes one or two other minor issues
- adds multistage docs to the README
- bump version to 0.2.0
- adds a NEWS file
- fixes #7

### CODE REVIEW

**Comment by aspiers** [comment]
I just removed misleading info from https://github.com/sosedoff/capistrano-unicorn/wiki/Using-capistrano-unicorn-with-multistage-environment regarding `app_env`.  However in future I think we should avoid storing docs in the wiki and instead store them in the git repo, because it's crucial that docs are coupled to the code they are documenting.  When a commit changes the code, it must also update the corresponding docs.  If they are in different places they can get out of sync far too easily.

**Comment by sosedoff** [comment]
@aspiers we can use "docs" folder to store manuals, better than on-site wiki

**Comment by aspiers** [comment]
Rebased after merge of #69.

**Comment by aspiers** [comment]
@sosedoff Agreed!  Luckily there is only one wiki page at the moment, and this pull request makes that obsolete anyway ...

**Comment by aspiers** [comment]
Any feedback?

**Comment by sfsekaran** [comment]
This all looks good to me, after a quick code review. It's all straightforward.

**Comment by aspiers** [comment]
@sfsekaran Thanks!  Should I merge then?  Not sure what the protocol is for how many +1s are required for this.

**Comment by aspiers** [comment]
OK, I think I'm done now.  I ended up making several more changes, including a fix for #7, i.e. auto-detection of the pid file path from the unicorn config.  I also added a `NEWS.md` file since all these changes could get a bit confusing, and are not 100% backwards-compatible.

Would _greatly_ appreciate someone testing this branch, since there are quite a lot of changes and I could have broken something (although I took great care not to!)

**Comment by aspiers** [comment]
Hmm, I'll have to rebase this now that we have a test suite :-/

**Comment by sfsekaran** [comment]
It would be awesome if you had time to write a few tests!

```
—
```

Sathya Sekaran

**Comment by aspiers** [comment]
Already working on it :)

**Comment by aspiers** [comment]
Almost finished this yesterday, will push soon ...

**Comment by aspiers** [comment]
OK, this has pretty thorough tests now, and I fixed a few minor issues whilst writing them.  So I'm pretty confident this is good to merge :)

**Comment by aspiers** [comment]
Please can someone review and merge?

**Comment by sfsekaran** [comment]
@aspiers Have you tested this out on a production env yet? It all looks good to me otherwise.

**Comment by aspiers** [comment]
Yes I'm using it to deploy two public apps (although they are tiny and low risk).  The new `unicorn:show_vars` task helps build confidence that it is calculating the right values, before you run any task which actually deploys anything.  But the test suite is also pretty comprehensive at this point.

**Comment by sfsekaran** [comment]
@aspiers Sounds great. Merging.

**Comment by sfsekaran** [comment]
@sosedoff When you get a chance--it's time for that gem release to v0.2.0.

**Comment by sfsekaran** [comment]
@aspiers Thank you for all the hard work! This was an excellent effort. I especially appreciate the attention to documentation here.

**Comment by aspiers** [comment]
@sfsekaran Thanks :)  I hate the idea of anyone else being confused by the docs in the same way I was, so I had to fix them :)

**Comment by sosedoff** [comment]
When i run test suite i get 4 failures even though travis build passes. Ruby 2.0.0p247:

```
Failures:

  1) CapistranoUnicorn::CapistranoIntegration loaded into a configuration testing variables app paths app in current_path it should behave like an app in path should auto-detect pid file from primary unicorn config
     Failure/Error: @configuration.fetch(:unicorn_pid).should == pid_file
       expected: "/path/to/pid/from/config/file"
            got: "/path/to/myapp/tmp/pids/unicorn.pid" (using ==)
     Shared Example Group: "an app in path" called from ./spec/capistrano_integration_spec.rb:93
     # ./spec/capistrano_integration_spec.rb:60:in `block (6 levels) in <top (required)>'

  2) CapistranoUnicorn::CapistranoIntegration loaded into a configuration testing variables app paths app in current_path it should behave like an app in path should auto-detect pid file from stage unicorn config
     Failure/Error: @configuration.fetch(:unicorn_pid).should == pid_file
       expected: "/path/to/pid/from/stage/config/file"
            got: "/path/to/myapp/tmp/pids/unicorn.pid" (using ==)
     Shared Example Group: "an app in path" called from ./spec/capistrano_integration_spec.rb:93
     # ./spec/capistrano_integration_spec.rb:60:in `block (6 levels) in <top (required)>'

  3) CapistranoUnicorn::CapistranoIntegration loaded into a configuration testing variables app paths app in a subdirectory it should behave like an app in path should auto-detect pid file from primary unicorn config
     Failure/Error: @configuration.fetch(:unicorn_pid).should == pid_file
       expected: "/path/to/pid/from/config/file"
            got: "/path/to/myapp/mysubdir/tmp/pids/unicorn.pid" (using ==)
     Shared Example Group: "an app in path" called from ./spec/capistrano_integration_spec.rb:103
     # ./spec/capistrano_integration_spec.rb:60:in `block (6 levels) in <top (required)>'

  4) CapistranoUnicorn::CapistranoIntegration loaded into a configuration testing variables app paths app in a subdirectory it should behave like an app in path should auto-detect pid file from stage unicorn config
     Failure/Error: @configuration.fetch(:unicorn_pid).should == pid_file
       expected: "/path/to/pid/from/stage/config/file"
            got: "/path/to/myapp/mysubdir/tmp/pids/unicorn.pid" (using ==)
     Shared Example Group: "an app in path" called from ./spec/capistrano_integration_spec.rb:103
     # ./spec/capistrano_integration_spec.rb:60:in `block (6 levels) in <top (required)>'
```

**Comment by aspiers** [comment]
This means the pid file auto-detection, which involves running `unicorn -c` on a temporary config file, is failing.  Maybe you don't have unicorn installed?  There is no development dependency on it, and there probably should be ... which begs the question why the Travis runs are succeeding.  Weird.

**Comment by sfsekaran** [comment]
Maybe Travis uses Unicorn. :'D

**Comment by sosedoff** [comment]
I added debug into build steps, there is no unicorn installed. See the build https://travis-ci.org/sosedoff/capistrano-unicorn/jobs/11100220

**Comment by aspiers** [comment]
Weird, I don't know why yours is failing then.  But it should be really easy for you to debug - the code is super simple!

**Comment by sfsekaran** [comment]
Any movement on this? It bothers me--I see four failures locally as well.

**Comment by aspiers** [comment]
@sfsekaran I do not see any failures, just warnings, e.g.

```
An expectation of :success? was set on nil. Called from /home/adam/.GIT/3rd-party/capistrano-unicorn/spec/config_spec.rb:36:in `block (6 levels) in <top (required)>'. Use allow_message_expectations_on_nil to disable warnings.
```

I did a git bisect, and the warnings arise from 9c355a54 in #74 which you merged into `master`.

**Comment by sfsekaran** [comment]
@aspiers Note that I merged #74 fairly recently, and I saw four failures before I paired on it.

**Pull request merged**
