### PR TITLE
Make it easier to find example config

### PR DESCRIPTION
**Pull request by aspiers**

### CODE REVIEW

**Comment by sosedoff** [comment]
Btw, i've made a change, so you dont have to put config under unicorn folder, saving it as `config/unicorn.rb` will also work. Capistrano will check for global unicorn file first, then check for config under unicorn folder.

**Comment by aspiers** [comment]
Wouldn't it be better to check for the environment-specific config under `unicorn/` first rather than second?  Or do you mean that you load both, and the second can override the first?

**Comment by sosedoff** [comment]
It loads either the primary config `config/unicorn.rb` or env-specific one. The reason why it behaves this way is to keep things simple. Plus i had a bunch requests to implement that.

**Comment by aspiers** [comment]
In that case it should prefer the env-specific one to the global one surely?

**Pull request merged**
