### PR TITLE
Allow to defined arbitrary options for unicorn

### PR DESCRIPTION
**Pull request by cschramm**
Scenario: One wants to run multiple instances of the same application (e. g. staging and production).

Solution in current master: Move config/unicorn.rb to config/unicorn/staging.rb and config/unicorn/production.rb and use different listen statements. I think this is ugly since 99 % of those files will be duplication and you will need another one for development. So you probably duplicate your unicorn configuration to at least three files.

Solution with this patch: set :unicorn_options, '--host 127.0.0.1 --port 8001' for one stage and set :unicorn_options, '--host 127.0.0.1 --port 8002' for the other one.

The underlying problem is that environment-specific configuration files for unicorn do not include a common configuration file, while for capistrano they do.

### CODE REVIEW

**Comment by cschramm** [comment]
Any feedback?

**Comment by sfsekaran** [comment]
Bear with me, but couldn't you simply require the base configuration file `config/unicorn.rb` from `config/unicorn/production.rb` and `config/unicorn/staging.rb`? They're just ruby after all, right?

**Comment by cschramm** [comment]
Valid point. This works, but has a few gotchas:

If config/unicorn.rb exists, config/unicorn/*.rb is not considered. You have to give it another name, e. g. config/unicorn/_common.rb

require'ing the common file does not work, since the unicorn config file is evaluated in a Unicorn::Configurator context, while require always switches to a global context, where the unicorn specific methods do not exist.

Thus one of my stage-specific files looks like this:

```
file = "#{File.dirname(config_file)}/_common.rb"

instance_eval(File.read(file), file)

listen '127.0.0.1:8001'
```

Thanks! :smiley:

**Comment by sfsekaran** [comment]
Interesting. Thanks for the followup! :zap:

**Pull request closed without merging**
