### PR TITLE
app environment independent of unicorn environment

### PR DESCRIPTION
**Pull request by tlimp**
useful for multistage deployments:
i.e. unicorn-config differs between staging and production servers but
the app should run in production environment on both.

Would you mind integrating this change into yours.

Kind regards, tehael

### CODE REVIEW

**Comment by sosedoff** [comment]
Could you provide a sample configuration so i can understand the use case?

**Comment by tlimp** [comment]
Hi,

for most of my projects I'm setting a staging server where the client
can check the changes before they go to production.
I'm using the multistage capistrano extension to configure the different stages.
Since I want the staging to behave just like production I run the
application in the production environment (only database
configurations differ between stages). On the other side I do not like
to have different files in config/environments which contents must be
kept in sync.

For some reasons, sometimes these deployment-stages are on the same
machine as different virtual-host configurations in nginx. Therefor I
cannot use the same "production" unicorn configuration for the
different stages, since those may conflict on for example tcp-ports.

To put long things short, I make a distinction between
deployment-stages and application-(runtime)-environment and the
unicorn-configuration depends more on the deployment-stage than on the
application-environment.

Hope that helps, kind regards,
tehael

2011/12/18 Dan Sosedoff
reply@reply.github.com:

**Comment by sosedoff** [comment]
Merged

**Comment by tlimp** [comment]
thanks a lot

2011/12/18 Dan Sosedoff
reply@reply.github.com:

**Pull request merged**
