### PR TITLE
Don't send debugging to stderr

### PR DESCRIPTION
**Pull request by astropanic**
Removing 

```
set -x
```

because it marks properly working tasks with the "err" indicator

### CODE REVIEW

**Comment by phillbaker** [comment]
Hey, this is much appreciated! :+1: It's not crucial, but it's annoying/unnerving to see lots of red in a deploy script.

Any chance this can get released soon?

**Comment by sfsekaran** [comment]
@phillbaker : Please use the github master HEAD version (or point to a specific commit ref for now).
@sosedoff : It would be nice to get a gem version bump. I'm totally willing to take responsibility for that if you want to give me permission on rubygems.org.

**Comment by sosedoff** [comment]
Pushed. I can check out how to set permissions later

**Comment by sfsekaran** [comment]
@sosedoff Thanks man.

**Comment by phillbaker** [comment]
@sosedoff much appreciated! Thank youl.

**Pull request merged**
