### PR TITLE
minor configuration changes

### PR DESCRIPTION
**Pull request by maorhayoun**
unicorn pid file should be placed at shard path location by default.
unicorn execution should use the unicorn_environment directly (and if not set, use the app_env fallback) 

happy to be corrected otherwise

### CODE REVIEW

**Comment by aspiers** [comment]
Thanks for the report.

You are right that the pid file should usually be within the `shared/` directory, however I think autodetection as described in #7 is a much better approach for the reasons I mentioned there.

Your other change is not quite right - see #70 for what I believe is the correct solution.

Therefore I suggest closing this PR in favour of #7 and #70.

**Comment by maorhayoun** [comment]
no argument about autodetection of pid path as the correct solution, 
but as I see it, if no specific override is done to indicate different none-the-usual path for the pid file - 
default path should still be valid

**Comment by aspiers** [comment]
Agreed, and that's why I added ed30b08 to #70 which will take care of this.

**Comment by aspiers** [comment]
Actually I just remembered that capistrano already automatically sets up a symlink from `#{current_path}/tmp/pids` to `#{shared_path/tmp/pids}` by default, so ed30b08 is unnecessary...

**Pull request closed without merging**
