### PR TITLE
Fixed current_path fetching with capistrano/multistage

### PR DESCRIPTION
**Pull request by dmeremyanin**
If using capistrano with multistage and set `deploy_to` variable in `deploy/production.rb` and `deploy/staging.rb`, then `current_path` on unicorn's tasks will be `/u/apps/...`. Maybe it's capistrano's bug, but this PR fixes that.

Also, removed some `rescue` calls.

### CODE REVIEW

**Comment by alexandru-calinoiu** [comment]
please merge this, I have the same issue

**Comment by nooga** [comment]
+1

**Comment by aishek** [comment]
+1

**Comment by hirocaster** [comment]
:+1:

**Comment by vitoravelino** [comment]
+1

**Comment by theleon** [comment]
+1

**Comment by elentok** [comment]
+1

**Comment by aspiers** [comment]
I can merge this if someone can explain to me why `current_path` should work and `fetch(:current_path)` doesn't.  I'd also like to know why the `rescue` calls were removed.  Ideally they should be in a separate commit.

**Comment by dmeremyanin** [comment]
Sorry, i'm used capistrano-unicorn v0.1.6 from rubygems, but this issue is resolved on master.

v0.1.6:

``` ruby
_cset(:variable, current_path) # current_path == /u/apps/...
```

master:

``` ruby
_cset(:variable) { current_path } # correct
```

Please, release a new version.
Thanks!

**Comment by mobileg23** [comment]
Thanks for the great work.

+1 to please, release a new version! Thanks

**Pull request closed without merging**
