### PR TITLE
Ability to launch Unicorn as a different user than the deployer

### PR DESCRIPTION
**Pull request by BMorearty**
With this change, capistrano-unicorn can run Unicorn master (and there Unicorn slaves) as a different user than the deployer.

Sometimes people prefer to use a privileged user for deploying apps and a less-privileged user for running apps. With this change, they can. Here's how:

``` ruby
set :unicorn_runner, true   # Run Unicorn as the :runner user ("app" by default)
set :use_sudo, true         # So deployer can launch Unicorn as the :runner user
# set :runner, "web"        # Optionally override Capistrano's :runner variable
```

This feature relies on Capistrano's existing `:runner` setting, which is the name of the user who will be running the web app. It defaults to `"app"` but can be overridden with `set :runner, "username"`. 

Or you can use a string to choose which user rather than relying on Capistrano's `:runner`:

``` ruby
set :unicorn_runner, "web"   # Run Unicorn as the "web" user
set :use_sudo, true          # So deployer can launch Unicorn as the :runner user
```

The new `unicorn_runner` setting defaults to `false`, keeping is the existing behavior of capistrano-unicorn.

Resolves issue sosedoff/capistrano-unicorn#22.

### CODE REVIEW

**Comment by BMorearty** [comment]
By the way, when Unicorn runs as a different user there are some file permissions that need to be fixed up. I did not include this in the pull request because I wasn't totally sure if it was generally applicable. But I think it is.

To be specific, the `unicorn_runner` user needs to be able to write to the `tmp` directory. And in some apps (e.g., apps that use CarrierWave for uploads), that user also needs to be able to create new subdirectories under `public`.

Here's what I did in my local deploy script. If you think this should be embedded in the pull request that's fine, or it could be added to the readme:

``` ruby
namespace :deploy do
  before "deploy:start",   "deploy:fix_permissions"
  after  "deploy:restart", "deploy:fix_permissions"

  task :fix_permissions, :roles => :app, :except => { :no_release => true } do
    run "#{try_sudo} chmod 775 #{current_path}/tmp"
    run "#{try_sudo} chmod 775 #{current_path}/public"
    run "#{try_sudo} chown #{user}:#{fetch(:unicorn_runner)} #{current_path}/tmp"
    run "#{try_sudo} chown #{user}:#{fetch(:unicorn_runner)} #{current_path}/public"
  end
end
```

Note that the way I wrote `fix_permissions` only works if `unicorn_runner` is a user name, not `true`. It would have to be modified to support `true`.

**Comment by sosedoff** [comment]
Also, why not use `unicorn_user` definition instead ?

**Comment by BMorearty** [comment]
Good question. I used `unicorn_runner` to follow the Capistrano convention, where they use `runner` to indicate the username of the use will run the web app.

I found the convention by looking at Capistrano's `try_runner` method, which looks for a variable called `:runner`. The `try_runner` comment says:

``` ruby
# Same as sudo, but tries sudo with :as set to the value of the :runner
# variable (which defaults to "app").
```

But a Google search indicates that use of "runner" doesn't seem widely used, and it also seems to have a dual purpose: for running deploy-time commands and for running the app. I think it makes sense to skip it altogether and just call it `unicorn_user`, and require a string (not support having `true` fall back on `runner`).

If you're in favor of that, I would be happy to make the change and test it with my app that is using my branch.

**Comment by sosedoff** [comment]
I think the best approach here would be a double-fallback. So we check if `unicorn_user` is defined first, then fallback to `unicorn_runner` and vise versa. This would allow people to use both without confusion. 

Thoughts ?

**Comment by BMorearty** [comment]
No, if I understand you right I don't think anyone would use `unicorn_runner` without being told to by some documentation somewhere. It's not something that ever existed before. So I don't think falling back on it serves any purpose. It just ends up allowing two variable names for one thing.

There is potential value in falling back on `runner`, which is why I did that in my original pull request, since it's an existing concept. 

How about this: I'll change the variable name to `unicorn_user` since that's a more obvious/clear name, and take out support for `true` to fallback on `runner`. If someone wants it to be the same as `runner` they can just set it to be the same.

**Comment by sosedoff** [comment]
Ok, that'll work for me.

**Comment by BMorearty** [comment]
I made the change but have not yet tested it. Check it out, but give me a minute.

I also improved something else. I felt weird about forcing people to set `use_sudo` to `true` just for this one feature. But I realized that if I change `try_sudo` to `sudo`, there's no need to force them to change another global setting in their cap script. `sudo` will always use sudo, regardless of any other variable settings.

This makes the setting less intrusive.

**Comment by BMorearty** [comment]
I tested the change. It works.

**Comment by BMorearty** [comment]
@sosedoff Any chance you could merge this in? I made the changes we discussed and I tested it. Thanks.

**Comment by sosedoff** [comment]
Sure thing

**Pull request merged**
