### PR TITLE
Move utility methods to a module to reduce load_into method complexity

### PR DESCRIPTION
**Pull request by Tonkpils**
I paired up for a bit with @sfsekaran and decided to break up the methods defined into an utility module.

### CODE REVIEW

**Comment by sfsekaran** [comment]
Travis passes, and this is a relatively simple change, reducing our monolithic method's LOC at the very least. Merging!

**Comment by sosedoff** [comment]
Make sure the indentation is not broken

**Comment by sfsekaran** [comment]
Nice catch. I really hate VIM's autoindent. I'll fix it.

**Comment by sfsekaran** [comment]
Fixed: a4c7f499d11f17ac1a5581476ce909d8665ded5c

**Pull request merged**
