### PR TITLE
Support for setting config file paths & file names.

### PR DESCRIPTION
**Pull request by jasiek**

### CODE REVIEW

**Comment by jasiek** [comment]
ping!

**Comment by sfsekaran** [comment]
I see nothing wrong with this change. Anyone else object to merging this?

**Comment by penso** [comment]
Please merge this, needed it right now.

**Comment by aspiers** [comment]
Looks good to me.

**Comment by sfsekaran** [comment]
Voila

**Comment by penso** [comment]
:+1:

**Comment by sosedoff** [comment]
Will push a new version to rubygems now

**Pull request merged**
