### PR TITLE
Unicorn config selection

### PR DESCRIPTION
**Pull request by sonnysideup**
A lot of folks using Unicorn do not use environment specific unicorn configuration files. Instead, they use a single file located directly under their project's config dir ( i.e. config/unicorn.rb ). This change allows for people to follow that convention but also maintains compatibility with env-specific files.

### CODE REVIEW

**Comment by sosedoff** [comment]
This looks good to me. I'll test and merge.

**Comment by erickt** [comment]
Any chance this could get merged? I just into this problem.

**Comment by sosedoff** [comment]
Check out new code, now capistrano-unicorn will try to load `config/unicorn.rb` first, and if file does not exists it will fall back to `config/unicorn/#{environment}.rb`

**Comment by sonnysideup** [comment]
thx dude

**Pull request closed without merging**
