### PR TITLE
:reload now does HUP instead of USR2

### PR DESCRIPTION
**Pull request by bengl**
In every environment I've worked on with unicorn, we've sent a HUP signal to unicorn instead of USR2, to do a "hot reload" of the application. To that end, I've made the :reload task send a HUP, and left USR2 in the restart task.

I think this should be the default behavior, so I've left the line

```
after "deploy:restart", "unicorn:reload"
```

as is. Thoughts on this?

### CODE REVIEW

**Comment by bengl** [comment]
process_exists was also causing me problems. fixed that.

**Comment by sosedoff** [comment]
Updated tasks, but there might be a potential problem when `preload_app` is enabled. 

Check docs - http://unicorn.bogomips.org/SIGNALS.html

Do you use `preload_app true` in your apps ?

**Comment by bengl** [comment]
I use <code>preload_app false</code>, with HUP in mind. 

I was also thinking that perhaps the behavior here should be easily configurable since not everyone would necessarily need/want HUP, but I haven't made any changes toward this.

**Comment by sosedoff** [comment]
There are 2 tasks right now:

unicorn:reload - Uses HUP signal
unicorn:restart - Uses USR2 signal

Making it smart means i'd have to actually ready unicorn config file and detect if preload_app is set to true then automatically modify tasks. But it could be really confusing to people. 

Im also trying to create a simple solution for proper app reloading inside capistrano-unicorn. We'll see how it goes.

**Comment by omerisimo** [comment]
Hi,

According to the above thread, and the unicorn documentation, we should use the HUP signal when preload_app is set to false.
The HUP signal is sent with the unicorn:reload task.
However in the README documentation it states that:
after 'deploy:restart', 'unicorn:restart' # app IS NOT preloaded
after 'deploy:restart', 'unicorn:reload'  # app preloaded

This seems to be the other way around.
Am I missing something?

**Pull request closed without merging**
