### PR TITLE
Support for running Unicorn as a different user.

### PR DESCRIPTION
**Pull request by matadon**
Running appservers from within their own, unprivileged user accounts is important for security, so I've added this functionality to capistrano-unicorn.

My pull request doesn't change any of the defaults, so functionality shouldn't change for existing users.

For those that want to run unicorn via sudo, `set :unicorn_user, "appuser"` will do the trick.

### CODE REVIEW

**Comment by sosedoff** [comment]
Hi Don,

First of all, your fork uses an old code, see the updated file: https://github.com/sosedoff/capistrano-unicorn/blob/master/lib/capistrano-unicorn/capistrano_integration.rb

Second, you can set unicorn user and group in configuration, see `examples/rails3.rb` for details. Also, you can see all configuration options here: http://unicorn.bogomips.org/Unicorn/Configurator.html

Regarding reloading, there are 2 task as for now: `unicorn:restart` and `unicorn:reload`

**Comment by matadon** [comment]
I'll go ahead and move the functionality to work against the newer version of the codebase and send in a new pull request -- I was working against the file from the current gem version.

Regarding starting Unicorn as a different user, I'm aware that you can do this from the Unicorn config file, but this requires that you start Unicorn as root, and let it setuid/setgid when launching workers.

This makes sense if you need Unicorn to grab a low-numbered port, but if you're running it behind a load balancer, then there's no reason you can't just run the whole kit-and-caboodle as a separate, unprivileged user.

On top of that, in order to have Unicorn switch users, you still need to run Unicorn via sudo, as only root can call setuid and setgid. So, my patch is still useful.

**Comment by sosedoff** [comment]
If you're still interested in this functionality, please send a fresh patch / PR. Closing for now.

**Comment by xevix** [comment]
@matadon I'm also interested in this functionality. I deploy with a deploy user, but would like unicorn (master and workers) to run as 'nobody'. If you're still willing to add this let me know, otherwise I might give it a go.

**Pull request closed without merging**
