### PR TITLE
zero down time on unicorn restart

### PR DESCRIPTION
**Pull request by lidaobing**
- user can customize the sleep time after USR2 signal
- add `set -x` for verbose information on deploy

### CODE REVIEW

**Comment by sosedoff** [comment]
Tested? All good?

**Comment by lidaobing** [comment]
tested on my deploy process, no problem

**Comment by DavidAllison** [comment]
@sosedoff Hi Dan - any chance we could get this merged in, and perhaps some of the other issues related to it reviewed? I am happy to help analyze and debug (it seems that currently there is a conflict with the way the unicorn restart task works within capistrano-unicorn and the way most users are writing their unicorn.rb file's before and after_fork blocks).

**Comment by sfsekaran** [comment]
Any idea why?

**Comment by astropanic** [comment]
because 

```
set -x
```

sends output to STDERR and you see the "err" indicator in Capistrano in red.

This is not a error in itself (the task works properly) but will for sure bring confusion to people.
Marking something red with errors, while working correctly brings a lot of confusion.
I would suggest use STDERR for what it was designed for.
Sending everything to STDERR for debugging purpose is bad practice.
You can affect the destination for set -x, but only from Bash version >= 4.1 via the BASH_XTRACEFD, but please don't do it...

**Comment by sfsekaran** [comment]
I see. Yeah, I wouldn't want everything going through STDERR either. Please send over a pull request removing that. Unless anyone else has a good reason not to, I'm going to merge it straightaway.

**Comment by astropanic** [comment]
Here you go https://github.com/sosedoff/capistrano-unicorn/pull/54

**Comment by sfsekaran** [comment]
@astropanic :zap:

**Comment by nextofsearch** [comment]
Does this gem support zero-downtime deployment yet?
It seems like it is not working.

**Comment by sfsekaran** [comment]
@nextofsearch My knowledge of zero-downtime deployment options:
- `unicorn:restart`: :-1: This can sort of support it with a configurable timeout, which can be very finicky.
- `unicorn:reload`: :question: I don't use this one currently. Can anyone testify to its zero-downtime support?
- `unicorn:duplicate`: :+1: If you install the Unicorn `before_fork` hook, then yes! See: https://github.com/sosedoff/capistrano-unicorn/issues/40#issuecomment-16011353

**Comment by nextofsearch** [comment]
@sfsekaran thanks a lot!!

**Pull request merged**
